print("✨ 2026 Goals ✨")
print("❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️")
print("1️⃣ Complete CCNA")
print("2️⃣ Complete cert no 2")
print("3️⃣ Loose weight to become 52 kg or under")
print("4️⃣ Finish atleat 3 qurans ")
print("5️⃣ Finish 5 parah tafseer")
print("6️⃣ Learn to swim")
print("7️⃣ Buy an ipad")
print("8️⃣ Get a job - proper networking one")
print("9️⃣ Byheart surah baqara atleast 1 para")
print("🔟 Sweeter to Ammi and Abba")